import os

files = []

legion_paths = ['/home/ccearie/Scratch/SRTM_original',
                '/home/ccearie/Scratch/SRTM_first_rerun',
                '/home/ccearie/Scratch/SRTM']

file_lists = ['file_list.txt', 'file_list_1.txt', 'file_list_2.txt']

# file_list.txt is generated by running ls -R > file_list.txt on legion
for legion_path, file_list in zip(legion_paths, file_lists):
    with open(file_list, 'r') as f:
        for q in f.readlines():
            if q.endswith('.csv\n') and 'MChiSegmented' in q:
                clean = q.strip()
                folder = clean.split('MChiSegmented')[0][:-1]
                tmp = os.path.join(legion_path, folder)
                files.append(os.path.join(tmp, clean))

with open('raw_file_list_cleaned.txt', 'w') as f:
    for q in files:
        f.write(q + '\n')
